on:
  push:
  # workflow_dispatch:
    # inputs:
    #   logLevel:
    #     description: 'Log level'
    #     required: true
    #     default: 'warning'
    #     type: choice
    #     options:
    #       - info
    #       - warning
    #       - debug
    #   tags:
    #     description: 'Test scenario tags'
    #     required: true
    #     type: string
#  schedule:
#    - cron: "*/5 * * * *"
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug
        run: |-
          echo ${{ github.repository }}

      - name: Generate
        run: |-
          mkdir secrets
          echo '{"id":1, "password":27}' >> secrets/secret_a.jsonl

      # - name: Get Public Key
      #   run: |-
      #     gh api \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #     /repos/${{ github.repository }}/actions/secrets/public-key
      #   env:
      #     GH_TOKEN: ${{ secrets.GW_7DAYS_RWSECRETS }}

      - name: List
        run: |-
          gh secret set DEBUG_SECRET < secrets/secret_a.jsonl
        env:
          GH_TOKEN: ${{ secrets.GW_7DAYS_RWSECRETS }}

      # - name: Encrypt
      #   run: |-
      #     gh api \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #     /repos/${{ github.repository }}/actions/secrets/public-key

      # - name: Upload
      #   run: |-
      #     gh api \
      #     --method PUT \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #     /repos/${{ github.repository }}/actions/secrets/SECRET_NAME \
      #     -f "encrypted_value=c2VjcmV0" -f "key_id=012345678912345678"
      #   env:
      #     GH_TOKEN: ${{ secrets.GW_7DAYS_RWSECRETS }}

      - name: Check
        run: |-
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/actions/secrets/DEBUG_SECRET
        env:
          GH_TOKEN: ${{ secrets.GW_7DAYS_RWSECRETS }}

      - name: List
        run: |-
          gh secret list
        env:
          GH_TOKEN: ${{ secrets.GW_7DAYS_RWSECRETS }}
