on:
  push:
    branches:
      - NONEXISTENT_BRANCH
jobs:
  print-tag:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Debug  STRING_SECRET_GLOBAL
        run: |-
          length=${#STRING}
          for ((i = 0; i < length; i++)); do
            char="${STRING:i:1}"
            echo "Character at position $i: $char"
          done
        env:
          STRING: ${{ secrets.STRING_SECRET_GLOBAL }}
      - name: Debug STRING_SECRET_DEV
        run: |-
          length=${#STRING}
          for ((i = 0; i < length; i++)); do
            char="${STRING:i:1}"
            echo "Character at position $i: $char"
          done
        env:
          STRING: ${{ secrets.STRING_SECRET_DEV }}
      - name: Debug STRING_SECRET_BOTH
        run: |-
          length=${#STRING}
          for ((i = 0; i < length; i++)); do
            char="${STRING:i:1}"
            echo "Character at position $i: $char"
          done
        env:
          STRING: ${{ secrets.STRING_SECRET_BOTH }}
      - name: Test langsung pake - Debug STRING_SECRET_BOTH
        run: |-
          echo "${{ secrets.STRING_SECRET_BOTH }}" >> secretly-secret.txt
          cat secretly-secret.txt
      - name: Test echo
        run: |-
          echo "print secret ${{ secrets.STRING_SECRET_IS_SECRET }}"
          echo "print SECRET secret secret"
          echo "SECRET"
          echo "secret"
          echo "secret"
      - name: Test missing secret
        run: |-
          echo "print secret '${{ secrets.MISSING_SECRET }}'"
          if [ "${{ secrets.MISSING_SECRET }}" = "" ]; then
            echo "NO SECRET"
          fi
      - name: Test missing vars
        run: |-
          echo "print secret '${{ vars.MISSING_VARS }}'"
          if [ "${{ vars.MISSING_VARS }}" = "" ]; then
            echo "NO VARS"
          fi

          
