on:
  workflow_call:
  
jobs:
  call-work:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verdict
        run: |-
          echo -e "secret_1=hello" > ./secrets_b/secrets2.txt

      - name: Verdict
        run: |-
          cat secrets_b/secrets2.txt
                
      - uses: actions/upload-artifact@v4
        with:
          name: 'secrets2'
          path: './secrets_b/secrets2.txt'
          if-no-files-found: 'error'
          overwrite: true
