on:
  push:
  
jobs:
  call-work:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verdict
        run: |-
          echo -e "secret_1=hello" > secrets_b/secrets2.txt

      - name: Verdict
        run: |-
          cat secrets_b/secrets2.txt

  print-tag:
    runs-on: ubuntu-latest
    needs: call-work
    steps:
      - name: Verdict
        run: |-
          cat secrets_b/secrets2.txt
