on:
  push:
    branches:
      - NONEXISTENT_BRANCH

jobs:
  call-work:
    uses: ./.github/workflows/sub.yml
  print-tag:
    runs-on: ubuntu-latest
    needs: call-work
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: secrets2
          path: './secrets_b/'
    
      - name: Verdict
        run: |-
          cat secrets_b/secrets2.txt
          
