name: Env test 3

run-name: Env test 3 - ${{ inputs.environment || 'dev' }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: environment
        default: stg
        required: true
      test_number_negative:
        description: "negative number"
        type: string
        default: '-1'
        required: true
      list:
        description: "list"
        type: string
        default: all
        required: true
      no_default:
        description: "no_default"
        type: string
        required: true
jobs:
  env-test:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment || 'dev' }}
    steps:
      - name: env
        run: |-
          echo ${{ inputs.environment }}
      - name: test_number_negative
        run: |-
          echo ${test_number_negative_env}
        env:
          test_number_negative_env: ${{ inputs.test_number_negative || '-1' }}

      - name: Listlist
        run: |-
          if [ "${LISTLIST}" = "" ] || [ "${LISTLIST}" = "all" ]
          then
            echo "listlist is blank or all, check: '${LISTLIST}'"
          else
            echo "listlist is unique, check: '${LISTLIST}'"
          fi
        env:
          LISTLIST: ${{ inputs.list || 'all' }}

      - name: nodefault
        run: |-
          echo "'${nodefaultttt}'"
        env:
          nodefaultttt: ${{ inputs.no_default || 'lah bisa kosong' }}

      - name: Debug STRING_SECRET_BOTH
        run: |-
          length=${#STRING}
          for ((i = 0; i < length; i++)); do
            char="${STRING:i:1}"
            echo "Character at position $i: $char"
          done
        env:
          STRING: ${{ secrets.STRING_SECRET_BOTH }}
